# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "MakeAll Gohugo Theme"
license = "MIT"
licenselink = "https://github.com/ranuzz/makeall-hugo-theme/blob/main/LICENSE.md"
description = "A Base theme for building full featured Hugo sites"
homepage = "https://github.com/ranuzz/makeall-hugo-theme"
tags = ["website", "starter", "responsive", "Disqus", "blog", "Tachyons", "Multilingual"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = "0.64.0"

[author]
  name = "ranuzz"
  homepage = "https://makeall.dev"
