title = "makeall-demo"
baseURL = "https://makeall.dev"
languageCode = "en-us"
theme = "makeall-hugo-theme"
themesDir = "../.."
resourceDir = "../resources"

DefaultContentLanguage = "en"
Paginate = 8
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = "/images/logo/logo32x32.jpeg"
  author = "ranuzz"
  contents = ['posts', 'notepad']
  searchcontents = ['posts', 'notepad']
  showtags = false
  showsearch = true
  hidden_site_logo = "https://makeall.dev/images/logo/logo.png"
  description = "Example Site makeall.dev hugo theme"
  facebook = ""
  twitter = "https://twitter.com/ranuzzzz"
  instagram = ""
  youtube = ""
  github = "https://github.com/ranuzz/"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  background_color_class = "bg-orange"
  background_color_accent_class = "bg-washed-red"
  background_color_body_class = "bg-washed-red"
  background_color_toc_class = "bg-light-red"
  recent_posts_number = 4
  body_classes = "avenir bg-washed-red"
  show_reading_time = true
  post_content_classes = "avenir bg-washed-red"
  custom_css = ["css/makeall.css"]


[menu]

  [[menu.main]]
    identifier = "posts"
    name = "Articles"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "notepad"
    name = "Notepad"
    url = "/notepad/"
    weight = 3

  [[menu.front]]
    identifier = "Home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.front]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2